spring:
  application:
    name: speakview
  datasource:
    url: jdbc:postgresql://${EC2_HOST}:5432/speakview
    username: speakview
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false